-- Seed di 200 nuove domande quiz (id 151-350), a sostituire il tema "mondiali_2026"
-- ormai datato. Quattro categorie da 50 domande ciascuna: storia_calcio,
-- trasferimenti_storici, spogliatoio, maglie_sponsor.
insert into public.quiz_questions (id, question, options, correct_index, theme) values
  (151, 'Quale nazionale ha vinto più Coppe del Mondo nella storia?', '["Germania","Brasile","Argentina","Italia"]'::jsonb, 1, 'storia_calcio'),
  (152, 'In quale anno si è giocato il primissimo Mondiale di calcio?', '["1926","1930","1934","1938"]'::jsonb, 1, 'storia_calcio'),
  (153, 'Quale paese ha vinto il Mondiale di calcio del 2006?', '["Francia","Brasile","Italia","Germania"]'::jsonb, 2, 'storia_calcio'),
  (154, 'Chi detiene il record di gol nella storia della Champions League?', '["Lionel Messi","Cristiano Ronaldo","Robert Lewandowski","Karim Benzema"]'::jsonb, 1, 'storia_calcio'),
  (155, 'Quale squadra ha vinto più edizioni della Champions League/Coppa dei Campioni?', '["Milan","Bayern Monaco","Real Madrid","Liverpool"]'::jsonb, 2, 'storia_calcio'),
  (156, 'In quale stadio l''Inghilterra gioca tradizionalmente le partite casalinghe della nazionale?', '["Old Trafford","Wembley","Anfield","Emirates Stadium"]'::jsonb, 1, 'storia_calcio'),
  (157, 'Quale nazionale ha vinto l''Europeo di calcio nel 2021 (edizione 2020 rinviata)?', '["Inghilterra","Spagna","Italia","Francia"]'::jsonb, 2, 'storia_calcio'),
  (158, 'Chi è il capocannoniere di sempre della Serie A?', '["Francesco Totti","Silvio Piola","Gunnar Nordahl","José Altafini"]'::jsonb, 1, 'storia_calcio'),
  (159, 'Quante squadre parteciperanno alla fase finale del Mondiale a partire dal 2026?', '["32","36","48","40"]'::jsonb, 2, 'storia_calcio'),
  (160, 'Quale calciatore ha vinto il maggior numero di Palloni d''Oro nella storia?', '["Cristiano Ronaldo","Michel Platini","Lionel Messi","Johan Cruijff"]'::jsonb, 2, 'storia_calcio'),
  (161, 'In che anno il Brasile ha vinto il suo primo Mondiale?', '["1950","1958","1962","1970"]'::jsonb, 1, 'storia_calcio'),
  (162, 'Quale nazionale ha raggiunto la finale dei Mondiali per ben 3 volte senza mai vincerlo?', '["Olanda","Ungheria","Svezia","Cecoslovacchia"]'::jsonb, 0, 'storia_calcio'),
  (163, 'Chi allenò l''Italia nella vittoria del Mondiale 2006?', '["Giovanni Trapattoni","Marcello Lippi","Cesare Prandelli","Arrigo Sacchi"]'::jsonb, 1, 'storia_calcio'),
  (164, 'Quale squadra vinse la prima edizione della Champions League col nuovo formato (1992-93)?', '["Milan","Marsiglia","Barcellona","Real Madrid"]'::jsonb, 1, 'storia_calcio'),
  (165, 'In quale nazione si disputò il Mondiale del 1994?', '["Messico","Stati Uniti","Brasile","Francia"]'::jsonb, 1, 'storia_calcio'),
  (166, 'Quale record detiene Miroslav Klose nella storia dei Mondiali?', '["Più presenze","Più gol complessivi","Più assist","Più cartellini gialli"]'::jsonb, 1, 'storia_calcio'),
  (167, 'In che anno si tenne il primo Mondiale ospitato in Asia?', '["1998","2002","2006","1994"]'::jsonb, 1, 'storia_calcio'),
  (168, 'Quale nazionale ha vinto il primo Europeo di calcio della storia (1960)?', '["Spagna","URSS","Italia","Germania Ovest"]'::jsonb, 1, 'storia_calcio'),
  (169, 'Quanti gol servono per un "hat-trick" nel calcio?', '["2","3","4","5"]'::jsonb, 1, 'storia_calcio'),
  (170, 'Quale nazionale ha vinto più Copa América nella storia?', '["Brasile","Argentina","Uruguay","Cile"]'::jsonb, 1, 'storia_calcio'),
  (171, 'Quale calciatore ha segnato una tripletta nella finale del Mondiale 2022 (Argentina-Francia)?', '["Lionel Messi","Kylian Mbappé","Ángel Di María","Julián Álvarez"]'::jsonb, 1, 'storia_calcio'),
  (172, 'Quale nazionale ha vinto la prima edizione della Coppa d''Africa (1957)?', '["Egitto","Etiopia","Sudan","Ghana"]'::jsonb, 0, 'storia_calcio'),
  (173, 'Quale squadra vinse il "Triplete" (Scudetto, Coppa Italia, Champions League) nel 2010?', '["Juventus","Milan","Inter","Napoli"]'::jsonb, 2, 'storia_calcio'),
  (174, 'In quale anno il Milan ha vinto la sua ultima Champions League fino al 2024?', '["2003","2007","2005","2010"]'::jsonb, 1, 'storia_calcio'),
  (175, 'Quale nazionale ha vinto il Mondiale femminile del 2023?', '["Stati Uniti","Spagna","Inghilterra","Germania"]'::jsonb, 1, 'storia_calcio'),
  (176, 'Quanti minuti dura complessivamente una partita di calcio regolamentare (esclusi recuperi)?', '["80","90","100","120"]'::jsonb, 1, 'storia_calcio'),
  (177, 'Quale nazionale ha vinto più Europei di calcio nella storia?', '["Germania","Spagna","Italia","Francia"]'::jsonb, 1, 'storia_calcio'),
  (178, 'Chi è considerato il primo vincitore del Pallone d''Oro della storia (1956)?', '["Alfredo Di Stéfano","Stanley Matthews","Ferenc Puskás","Raymond Kopa"]'::jsonb, 1, 'storia_calcio'),
  (179, 'In quale città ebbe luogo la tragedia dell''Heysel nel 1985?', '["Londra","Bruxelles","Torino","Madrid"]'::jsonb, 1, 'storia_calcio'),
  (180, 'Quale nazionale ha vinto il Mondiale 2022 in Qatar?', '["Francia","Argentina","Croazia","Marocco"]'::jsonb, 1, 'storia_calcio'),
  (181, 'Con quale nome fu istituita nel 1955 la competizione europea per club oggi chiamata Champions League?', '["Europa League","Coppa dei Campioni","Coppa delle Coppe","Supercoppa"]'::jsonb, 1, 'storia_calcio'),
  (182, 'Quale nazionale vinse la prima edizione della Nations League UEFA (2019)?', '["Olanda","Inghilterra","Portogallo","Svizzera"]'::jsonb, 2, 'storia_calcio'),
  (183, 'Quale calciatore ha vinto più Scarpe d''Oro europee nella storia?', '["Cristiano Ronaldo","Lionel Messi","Robert Lewandowski","Luis Suárez"]'::jsonb, 0, 'storia_calcio'),
  (184, 'Quale squadra detiene il record di punti in una singola stagione di Premier League?', '["Manchester City","Liverpool","Chelsea","Arsenal"]'::jsonb, 0, 'storia_calcio'),
  (185, 'In quale anno la Football League First Division inglese fu ribattezzata Premier League?', '["1988","1992","1995","1990"]'::jsonb, 1, 'storia_calcio'),
  (186, 'Quale nazionale detiene il record di titoli nel Mondiale Under 20 di calcio?', '["Argentina","Brasile","Portogallo","Spagna"]'::jsonb, 0, 'storia_calcio'),
  (187, 'Quale calciatore detiene il record di presenze con la maglia della nazionale italiana?', '["Fabio Cannavaro","Gianluigi Buffon","Paolo Maldini","Alessandro Del Piero"]'::jsonb, 1, 'storia_calcio'),
  (188, 'Quale nazionale ha vinto il Mondiale 1978, giocato in casa?', '["Argentina","Brasile","Uruguay","Cile"]'::jsonb, 0, 'storia_calcio'),
  (189, 'Chi ha vinto il Pallone d''Oro 2022?', '["Karim Benzema","Sadio Mané","Kevin De Bruyne","Robert Lewandowski"]'::jsonb, 0, 'storia_calcio'),
  (190, 'Quale squadra vinse la prima edizione dell''Europa League col nome attuale (2009-10)?', '["Atletico Madrid","Porto","Valencia","Fulham"]'::jsonb, 0, 'storia_calcio'),
  (191, 'In quale nazione si è giocato il Mondiale del 2018?', '["Brasile","Russia","Qatar","Germania"]'::jsonb, 1, 'storia_calcio'),
  (192, 'Quale nazionale ha vinto il Mondiale del 1998, giocato in Francia?', '["Brasile","Francia","Croazia","Olanda"]'::jsonb, 1, 'storia_calcio'),
  (193, 'Quanti calciatori compongono una squadra di calcio a 11 in campo, portiere incluso?', '["10","11","12","9"]'::jsonb, 1, 'storia_calcio'),
  (194, 'Quale calciatore ha vinto 5 Champions League in carriera (Manchester United + Real Madrid)?', '["Sergio Ramos","Cristiano Ronaldo","Karim Benzema","Luka Modrić"]'::jsonb, 1, 'storia_calcio'),
  (195, 'Quale nazionale ha vinto il primo Mondiale disputato in Sud America dopo l''Uruguay 1930?', '["Brasile","Argentina","Cile","Uruguay"]'::jsonb, 0, 'storia_calcio'),
  (196, 'In quale nazione furono codificate nel 1863 le prime regole moderne del calcio?', '["Italia","Inghilterra","Scozia","Francia"]'::jsonb, 1, 'storia_calcio'),
  (197, 'Quale nazionale ha vinto la Confederations Cup nella sua ultima edizione (2017)?', '["Cile","Germania","Portogallo","Messico"]'::jsonb, 1, 'storia_calcio'),
  (198, 'Quale record NON appartiene a Lionel Messi con la maglia dell''Argentina?', '["Più presenze in assoluto","Più Palloni d''Oro personali","Capitano del Mondiale 2022 vinto","Nessuno: li detiene tutti"]'::jsonb, 3, 'storia_calcio'),
  (199, 'Quale nazionale ha vinto la Coppa d''Africa 2023, disputata a inizio 2024?', '["Nigeria","Costa d''Avorio","Senegal","Marocco"]'::jsonb, 1, 'storia_calcio'),
  (200, 'Quale squadra italiana ha vinto più Scudetti nella storia?', '["Juventus","Milan","Inter","Roma"]'::jsonb, 0, 'storia_calcio'),
  (201, 'Quale trasferimento stabilì il record mondiale nel 2017 (222 milioni di euro)?', '["Neymar dal Barcellona al PSG","Mbappé al PSG","Ronaldo alla Juventus","Pogba al Manchester United"]'::jsonb, 0, 'trasferimenti_storici'),
  (202, 'Per quale cifra approssimativa Cristiano Ronaldo passò dal Real Madrid alla Juventus nel 2018?', '["~100 milioni €","~117 milioni €","~150 milioni €","~200 milioni €"]'::jsonb, 1, 'trasferimenti_storici'),
  (203, 'Da quale squadra arrivò Kylian Mbappé quando si trasferì al PSG?', '["Chelsea","Monaco","Lione","Marsiglia"]'::jsonb, 1, 'trasferimenti_storici'),
  (204, 'In quale anno Zinedine Zidane si trasferì dalla Juventus al Real Madrid per un record mondiale?', '["1998","2000","2001","2003"]'::jsonb, 2, 'trasferimenti_storici'),
  (205, 'Circa quanto pagò il Real Madrid per Zidane nel 2001, allora record mondiale?', '["~45 milioni €","~66 milioni €","~77 milioni €","~90 milioni €"]'::jsonb, 2, 'trasferimenti_storici'),
  (206, 'Da quale squadra arrivò Luis Suárez quando si trasferì al Barcellona nel 2014?', '["Ajax","Liverpool","Atletico Madrid","Porto"]'::jsonb, 1, 'trasferimenti_storici'),
  (207, 'Quale attaccante si trasferì dal Milan al PSG nel 2012?', '["Zlatan Ibrahimović","Mario Balotelli","Samuel Eto''o","Didier Drogba"]'::jsonb, 0, 'trasferimenti_storici'),
  (208, 'In che anno Diego Maradona si trasferì dal Barcellona al Napoli?', '["1982","1984","1986","1988"]'::jsonb, 1, 'trasferimenti_storici'),
  (209, 'Da quale squadra proveniva Erling Haaland quando si trasferì al Manchester City nel 2022?', '["Salisburgo","Borussia Dortmund","Molde","Lipsia"]'::jsonb, 1, 'trasferimenti_storici'),
  (210, 'Quale squadra acquistò Gareth Bale dal Tottenham nel 2013 per un record mondiale?', '["Real Madrid","Barcellona","Manchester United","PSG"]'::jsonb, 0, 'trasferimenti_storici'),
  (211, 'Circa per quale cifra il Real Madrid acquistò Gareth Bale nel 2013?', '["~65 milioni €","~85-100 milioni €","~120 milioni €","~150 milioni €"]'::jsonb, 1, 'trasferimenti_storici'),
  (212, 'Quale calciatore si trasferì dal Barcellona al PSG a parametro zero nel 2021?', '["Luis Suárez","Lionel Messi","Neymar","Gerard Piqué"]'::jsonb, 1, 'trasferimenti_storici'),
  (213, 'Da quale squadra brasiliana il Barcellona acquistò Neymar nel 2013?', '["Flamengo","Santos","San Paolo","Palmeiras"]'::jsonb, 1, 'trasferimenti_storici'),
  (214, 'Da quale squadra tornò Paul Pogba al Manchester United nel 2016, con un trasferimento record?', '["Juventus","Real Madrid","PSG","Monaco"]'::jsonb, 0, 'trasferimenti_storici'),
  (215, 'Quale squadra pagò la cifra più alta della storia della Premier League per un centrocampista (Moisés Caicedo, 2023)?', '["Arsenal","Chelsea","Manchester City","Liverpool"]'::jsonb, 1, 'trasferimenti_storici'),
  (216, 'Da quale club proveniva Jude Bellingham quando si trasferì al Real Madrid nel 2023?', '["Manchester City","Borussia Dortmund","Chelsea","Liverpool"]'::jsonb, 1, 'trasferimenti_storici'),
  (217, 'Quale squadra acquistò Romelu Lukaku dal Manchester United nel 2019?', '["Chelsea","Inter","Roma","Juventus"]'::jsonb, 1, 'trasferimenti_storici'),
  (218, 'Da quale squadra arrivò Antoine Griezmann quando si trasferì al Barcellona nel 2019?', '["Real Madrid","Atletico Madrid","Valencia","Siviglia"]'::jsonb, 1, 'trasferimenti_storici'),
  (219, 'Da quale squadra tornò Álvaro Morata alla Juventus nel 2020?', '["Chelsea","Atletico Madrid","Real Madrid","Siviglia"]'::jsonb, 1, 'trasferimenti_storici'),
  (220, 'Il trasferimento di Kaká dal Milal al Real Madrid nel 2009 stabilì cosa?', '["Il record mondiale del momento","Il primo trasferimento sopra i 60 milioni","Nessun record","Il trasferimento più caro per un brasiliano dei decenni successivi"]'::jsonb, 0, 'trasferimenti_storici'),
  (221, 'Da quale squadra il Manchester City acquistò Kevin De Bruyne nel 2015?', '["Chelsea","Wolfsburg","Werder Brema","Genk"]'::jsonb, 1, 'trasferimenti_storici'),
  (222, 'Quale centrocampista lasciò il Barcellona per il Bayern Monaco nel 2013?', '["Javier Mascherano","Jérôme Boateng","Thiago Alcântara","Dani Alves"]'::jsonb, 2, 'trasferimenti_storici'),
  (223, 'Quale squadra acquistò Virgil van Dijk dal Southampton nel 2018 per un record da difensore?', '["Manchester United","Liverpool","Chelsea","Manchester City"]'::jsonb, 1, 'trasferimenti_storici'),
  (224, 'Da quale squadra proveniva João Félix prima di trasferirsi all''Atletico Madrid nel 2019?', '["Porto","Sporting Lisbona","Benfica","Braga"]'::jsonb, 2, 'trasferimenti_storici'),
  (225, 'Quale attaccante ivoriano fu acquistato dal Chelsea nel 2004 dall''Olympique Marsiglia?', '["Didier Drogba","Yaya Touré","Salomon Kalou","Gervinho"]'::jsonb, 0, 'trasferimenti_storici'),
  (226, 'Da quale squadra francese il Real Madrid acquistò Karim Benzema nel 2009?', '["Marsiglia","Lione","Lille","Monaco"]'::jsonb, 1, 'trasferimenti_storici'),
  (227, 'Quale calciatore svedese ha giocato in carriera per Ajax, Juventus, Inter, Barcellona, Milan e PSG?', '["Zlatan Ibrahimović","Henrik Larsson","Freddie Ljungberg","Kim Källström"]'::jsonb, 0, 'trasferimenti_storici'),
  (228, 'Quale squadra acquistò Enzo Fernández dal Benfica nel 2023 per il record del club?', '["Chelsea","Arsenal","Manchester United","Newcastle"]'::jsonb, 0, 'trasferimenti_storici'),
  (229, 'Da quale squadra italiana proveniva Marco Verratti quando si trasferì al PSG nel 2012?', '["Inter","Pescara","Palermo","Atalanta"]'::jsonb, 1, 'trasferimenti_storici'),
  (230, 'Il trasferimento di Declan Rice all''Arsenal nel 2023 stabilì quale record?', '["Trasferimento più caro nella storia del club","Trasferimento più caro per un portiere","Nessun record","Primo giocatore inglese sopra i 50 milioni"]'::jsonb, 0, 'trasferimenti_storici'),
  (231, 'Da quale squadra proveniva Declan Rice prima dell''Arsenal?', '["Chelsea","West Ham United","Tottenham","Everton"]'::jsonb, 1, 'trasferimenti_storici'),
  (232, 'Quale centrocampista olandese si trasferì dall''Ajax al Barcellona?', '["Frenkie de Jong","Matthijs de Ligt","Memphis Depay","Donny van de Beek"]'::jsonb, 0, 'trasferimenti_storici'),
  (233, 'Quale difensore olandese lasciò l''Ajax per la Juventus nel 2019?', '["Frenkie de Jong","Matthijs de Ligt","Daley Blind","Nicolás Tagliafico"]'::jsonb, 1, 'trasferimenti_storici'),
  (234, 'Da quale squadra il Liverpool acquistò Mohamed Salah nel 2017?', '["Chelsea","Roma","Fiorentina","Basilea"]'::jsonb, 1, 'trasferimenti_storici'),
  (235, 'Quale attaccante argentino si trasferì dal River Plate al Manchester City nel 2022?', '["Julián Álvarez","Lautaro Martínez","Paulo Dybala","Ángel Di María"]'::jsonb, 0, 'trasferimenti_storici'),
  (236, 'Da quale squadra argentina proveniva Lautaro Martínez quando arrivò all''Inter nel 2018?', '["Racing Club","Boca Juniors","River Plate","Independiente"]'::jsonb, 0, 'trasferimenti_storici'),
  (237, 'Il trasferimento di Moisés Caicedo al Chelsea nel 2023 stabilì quale record?', '["Trasferimento più caro della storia Premier per un centrocampista","Nessun record","Primo colombiano sopra i 50 milioni","Primo ecuadoriano in Premier League"]'::jsonb, 0, 'trasferimenti_storici'),
  (238, 'Quale squadra tedesca vendette Erling Haaland al Manchester City nel 2022?', '["RB Salisburgo","Borussia Dortmund","Molde","Bayern Monaco"]'::jsonb, 1, 'trasferimenti_storici'),
  (239, 'Per quale club norvegese giocò Erling Haaland prima del trasferimento in Austria?', '["Molde","Rosenborg","Viking","Brann"]'::jsonb, 0, 'trasferimenti_storici'),
  (240, 'Da quale squadra arrivò Martin Ødegaard quando si trasferì definitivamente all''Arsenal?', '["Real Madrid","Real Sociedad","Vitesse","Strasburgo"]'::jsonb, 0, 'trasferimenti_storici'),
  (241, 'Quale squadra pagò la cifra più alta di sempre per un portiere con l''acquisto di Kepa Arrizabalaga nel 2018?', '["Chelsea","Real Madrid","Manchester United","Athletic Bilbao"]'::jsonb, 0, 'trasferimenti_storici'),
  (242, 'Da quale squadra arrivò Kepa Arrizabalaga quando si trasferì al Chelsea?', '["Real Madrid","Athletic Bilbao","Valencia","Siviglia"]'::jsonb, 1, 'trasferimenti_storici'),
  (243, 'Quale attaccante si trasferì dal Borussia Dortmund all''Arsenal nel 2018?', '["Pierre-Emerick Aubameyang","Alexandre Lacazette","Ousmane Dembélé","Nicolas Pépé"]'::jsonb, 0, 'trasferimenti_storici'),
  (244, 'Quale squadra acquistò Ousmane Dembélé dal Borussia Dortmund nel 2017, per sostituire Neymar?', '["Real Madrid","Barcellona","Atletico Madrid","PSG"]'::jsonb, 1, 'trasferimenti_storici'),
  (245, 'Da quale squadra il Bayern Monaco acquistò Harry Kane nel 2023?', '["Manchester City","Tottenham","Chelsea","Arsenal"]'::jsonb, 1, 'trasferimenti_storici'),
  (246, 'Il trasferimento di Harry Kane nel 2023 stabilì quale record per il Bayern Monaco?', '["Trasferimento più caro nella storia del club","Nessun record","Primo inglese in Bundesliga","Trasferimento più caro nella storia inglese"]'::jsonb, 0, 'trasferimenti_storici'),
  (247, 'Da quale squadra portoghese si trasferì Cristiano Ronaldo al Manchester United nel 2003?', '["Sporting Lisbona","Benfica","Porto","Braga"]'::jsonb, 0, 'trasferimenti_storici'),
  (248, 'Quale attaccante norvegese giocò per il Chelsea a metà anni 2000, precursore della generazione Haaland?', '["Ole Gunnar Solskjær (Man Utd, non Chelsea)","John Carew","Tore André Flo","Steffen Iversen"]'::jsonb, 2, 'trasferimenti_storici'),
  (249, 'Quale squadra vendette Neymar al Barcellona nel 2013?', '["Flamengo","Santos","Corinthians","Grêmio"]'::jsonb, 1, 'trasferimenti_storici'),
  (250, 'Il trasferimento di Neymar dal Barcellona al PSG nel 2017 fu il primo a superare quale soglia?', '["100 milioni €","150 milioni €","200 milioni €","250 milioni €"]'::jsonb, 2, 'trasferimenti_storici'),
  (251, 'Cosa fece Marco Materazzi che scatenò la testata di Zidane nella finale Mondiale 2006?', '["Un fallo duro","Una provocazione verbale","Uno sgambetto","Una spinta"]'::jsonb, 1, 'spogliatoio'),
  (252, 'In quale competizione avvenne la celebre testata di Zidane a Materazzi?', '["Europeo 2004","Mondiale 2006","Champions League 2005","Mondiale 2010"]'::jsonb, 1, 'spogliatoio'),
  (253, 'Quale allenatore pronunciò la celebre frase "Football, bloody hell!" dopo la finale di Champions League 1999?', '["Alex Ferguson","Arsène Wenger","José Mourinho","Pep Guardiola"]'::jsonb, 0, 'spogliatoio'),
  (254, 'Quale celebre discussione tattica pubblica esplose tra Ibrahimović e Guardiola al Barcellona?', '["Su un''automobile","Su una scelta tattica","Su uno sponsor","Sulla fascia da capitano"]'::jsonb, 1, 'spogliatoio'),
  (255, 'In quale libro autobiografico Zlatan Ibrahimović raccontò lo scontro con Guardiola al Barcellona?', '["\"Io, Ibra\"","\"Adrenalina\"","\"The Beautiful Game\"","\"Vincere\""]'::jsonb, 0, 'spogliatoio'),
  (256, 'Quale capitano della Roma pianse in diretta durante l''ultima partita della sua carriera nel 2017?', '["Francesco Totti","Daniele De Rossi","Alessandro Nesta","Antonio Cassano"]'::jsonb, 0, 'spogliatoio'),
  (257, 'La finale di Champions League 2005 (Istanbul) è famosa per la rimonta di quale squadra da 0-3 a 3-3?', '["Liverpool contro Milan","Milan contro Liverpool","Liverpool contro Real Madrid","Chelsea contro Milan"]'::jsonb, 0, 'spogliatoio'),
  (258, 'Quale gesto di esultanza è diventato il marchio di fabbrica di Cristiano Ronaldo dopo ogni gol?', '["Il \"Siuuu\" con salto ed esultanza","Il bacio al pallone","La corsa verso la bandierina","Le braccia larghe immobile"]'::jsonb, 0, 'spogliatoio'),
  (259, 'Quale celebre esultanza "a ballo con la bandierina" è associata a Roger Milla nei Mondiali 1990?', '["Ballo d''angolo con la bandierina","Salto con pugno chiuso","Bacio al terreno di gioco","Corsa a braccia aperte"]'::jsonb, 0, 'spogliatoio'),
  (260, 'Quale calciatore fu protagonista del celebre episodio della "Mano de Dios" nel Mondiale 1986?', '["Diego Armando Maradona","Pelé","Gary Lineker","Peter Shilton"]'::jsonb, 0, 'spogliatoio'),
  (261, 'Contro quale nazionale Maradona segnò anche il "Gol del secolo", nella stessa partita della "Mano de Dios"?', '["Inghilterra","Germania Ovest","Belgio","Italia"]'::jsonb, 0, 'spogliatoio'),
  (262, 'In quale anno avvenne la celebre rissa tra le panchine di Real Madrid e Barcellona con protagonista José Mourinho?', '["2011","2013","2015","2009"]'::jsonb, 0, 'spogliatoio'),
  (263, 'Quale allenatore fu coinvolto nel celebre incidente in cui colpì l''occhio di un assistente del Barcellona nel 2011?', '["José Mourinho","Carlo Ancelotti","Zinedine Zidane","Rafa Benítez"]'::jsonb, 0, 'spogliatoio'),
  (264, 'Quale calciatore rese celebre l''esultanza "aeroplanino" con le braccia aperte come ali?', '["Fabrizio Ravanelli","Filippo Inzaghi","Christian Vieri","Roberto Baggio"]'::jsonb, 0, 'spogliatoio'),
  (265, 'Da quale calciatore prende il nome il celebre rigore "a cucchiaio" (Panenka)?', '["Antonin Panenka","Johan Cruijff","Franz Beckenbauer","Michel Platini"]'::jsonb, 0, 'spogliatoio'),
  (266, 'Quale calciatore italiano rifece il rigore "alla Panenka" contro l''Inghilterra ai rigori di Euro 2012?', '["Andrea Pirlo","Mario Balotelli","Antonio Cassano","Leonardo Bonucci"]'::jsonb, 0, 'spogliatoio'),
  (267, 'Contro quale squadra Paolo Di Canio compì nel 2000 il celebre gesto di prendere il pallone con le mani invece di segnare a porta vuota?', '["Everton","Chelsea","Arsenal","Liverpool"]'::jsonb, 0, 'spogliatoio'),
  (268, 'Quale allenatore portoghese si definì per primo "The Special One" in conferenza stampa?', '["José Mourinho","André Villas-Boas","Carlos Queiroz","Fernando Santos"]'::jsonb, 0, 'spogliatoio'),
  (269, 'In quale occasione José Mourinho pronunciò per la prima volta "The Special One"?', '["Presentazione al Chelsea 2004","Presentazione al Real Madrid 2010","Presentazione all''Inter 2008","Presentazione al Manchester United 2016"]'::jsonb, 0, 'spogliatoio'),
  (270, 'Chi fu il capitano della Spagna che sollevò la Coppa del Mondo 2010?', '["Iker Casillas","Xavi Hernández","Carles Puyol","Sergio Ramos"]'::jsonb, 0, 'spogliatoio'),
  (271, 'Chi segnò il rigore decisivo per l''Italia nella finale Mondiale 2006 contro la Francia?', '["Fabio Grosso","Andrea Pirlo","Alessandro Del Piero","Francesco Totti"]'::jsonb, 0, 'spogliatoio'),
  (272, 'Quale fu la celebre esultanza di Fabio Grosso subito dopo il rigore decisivo del 2006?', '["Una corsa a perdifiato con la maglia sollevata","Ginocchia a terra in silenzio","Un salto sulla traversa","Un bacio al terreno"]'::jsonb, 0, 'spogliatoio'),
  (273, 'Quali due storici capitani della Juventus scelsero di restare in Serie B dopo Calciopoli nel 2006?', '["Del Piero e Buffon","Nedvěd e Trezeguet","Chiellini e Barzagli","Vialli e Baggio"]'::jsonb, 0, 'spogliatoio'),
  (274, 'Chi sbagliò il rigore decisivo nella finale Mondiale 1994 tra Italia e Brasile?', '["Roberto Baggio","Franco Baresi","Daniele Massaro","Alessandro Costacurta"]'::jsonb, 0, 'spogliatoio'),
  (275, 'Quale soprannome venne dato a Roberto Baggio per il suo stile elegante e la caratteristica acconciatura?', '["\"Il Divin Codino\"","\"Il Fenomeno\"","\"Pallone d''Oro\"","\"Il Principe\""]'::jsonb, 0, 'spogliatoio'),
  (276, 'Quale soprannome fu dato a Ronaldo (il brasiliano) per la sua esplosività atletica?', '["\"Il Fenomeno\"","\"Il Divin Codino\"","\"O Rei\"","\"Il Principe\""]'::jsonb, 0, 'spogliatoio'),
  (277, 'Quale storico soprannome fu dato a Pelé, traducibile come "Il Re"?', '["\"O Rei\"","\"Il Fenomeno\"","\"Pibe de Oro\"","\"Kaiser\""]'::jsonb, 0, 'spogliatoio'),
  (278, 'Quale soprannome storico fu dato a Diego Maradona, traducibile come "il ragazzo d''oro"?', '["\"Pibe de Oro\"","\"O Rei\"","\"Kaiser\"","\"Il Fenomeno\""]'::jsonb, 0, 'spogliatoio'),
  (279, 'Quale soprannome fu dato a Franz Beckenbauer per il suo ruolo di leader in campo?', '["\"Der Kaiser\"","\"Il Fenomeno\"","\"O Rei\"","\"Pibe de Oro\""]'::jsonb, 0, 'spogliatoio'),
  (280, 'Quale celebre gesto reso iconico da Alessandro Del Piero consisteva in un gol a giro da posizione defilata?', '["Il gol \"alla Del Piero\"","Il \"cucchiaio\"","La rovesciata","Il tacco"]'::jsonb, 0, 'spogliatoio'),
  (281, 'Con quale celebre maschera esultò Pierre-Emerick Aubameyang durante un derby londinese?', '["Maschera di Black Panther","Bandana","Fascia da capitano in bocca","Occhiali da sole"]'::jsonb, 0, 'spogliatoio'),
  (282, 'Quale celebre acconciatura rese famoso David Beckham negli anni 2000?', '["Il ciuffo/cresta di capelli","Basette lunghe","Barba incolta","Testa rasata"]'::jsonb, 0, 'spogliatoio'),
  (283, 'Quale allenatore serbo-italiano raccontò pubblicamente in conferenza stampa, a testa rasata, la sua battaglia contro la leucemia nel 2019?', '["Sinisa Mihajlović","Nemanja Vidić","Dejan Stanković","Miralem Pjanić"]'::jsonb, 0, 'spogliatoio'),
  (284, 'Chi fu il capitano dell''Italia che alzò il trofeo di Euro 2020 (disputato nel 2021)?', '["Giorgio Chiellini","Leonardo Bonucci","Gianluigi Donnarumma","Lorenzo Insigne"]'::jsonb, 0, 'spogliatoio'),
  (285, 'Chi parò il rigore decisivo per l''Italia nella finale di Euro 2020 contro l''Inghilterra?', '["Gianluigi Donnarumma","Salvatore Sirigu","Alex Meret","Wojciech Szczęsny"]'::jsonb, 0, 'spogliatoio'),
  (286, 'Quale allenatore è noto per sedersi sempre a bordo campo su un secchio rovesciato?', '["Marcelo Bielsa","Diego Simeone","Jorge Sampaoli","Mauricio Pochettino"]'::jsonb, 0, 'spogliatoio'),
  (287, 'Quale allenatore argentino è soprannominato "El Loco" per la sua intensità?', '["Marcelo Bielsa","Diego Simeone","Jorge Sampaoli","Mauricio Pochettino"]'::jsonb, 0, 'spogliatoio'),
  (288, 'Quale allenatore è noto per l''esultanza plateale a bordo campo diventata virale contro il Liverpool nel 2019/20?', '["Diego Simeone","Jürgen Klopp","Pep Guardiola","Antonio Conte"]'::jsonb, 0, 'spogliatoio'),
  (289, 'Quale soprannome ha Diego Simeone per il suo carattere combattivo?', '["\"El Cholo\"","\"El Loco\"","\"El Pibe\"","\"El Kun\""]'::jsonb, 0, 'spogliatoio'),
  (290, 'Quale allenatore italiano è noto per l''intensità emotiva a bordo campo, diventata virale sui social?', '["Antonio Conte","Carlo Ancelotti","Massimiliano Allegri","Roberto Mancini"]'::jsonb, 0, 'spogliatoio'),
  (291, 'Quale docu-serie calcistica ha reso celebri i discorsi di spogliatoio del Sunderland tra Championship e League One?', '["Sunderland ''Til I Die","All or Nothing","Drive to Survive","The Last Dance"]'::jsonb, 0, 'spogliatoio'),
  (292, 'Quale serie documentaristica Amazon ha seguito da vicino lo spogliatoio del Manchester City?', '["All or Nothing: Manchester City","Sunderland ''Til I Die","Take Us Home","First Team"]'::jsonb, 0, 'spogliatoio'),
  (293, 'Quale documentario ha mostrato i discorsi motivazionali di José Mourinho nello spogliatoio del Tottenham?', '["All or Nothing: Tottenham Hotspur","Sunderland ''Til I Die","Take Us Home","First Team"]'::jsonb, 0, 'spogliatoio'),
  (294, 'Quale documentario Netflix racconta la carriera e la vita privata di Neymar?', '["Neymar: O Caos Perfeito","The Last Dance","Sunderland ''Til I Die","Take Us Home"]'::jsonb, 0, 'spogliatoio'),
  (295, 'Quale celebre gesto di rispetto è diventato tradizione tra calciatori a fine partita, in particolare dopo i Mondiali?', '["Lo scambio delle maglie","Lo scambio dei gagliardetti soltanto","L''applauso reciproco","Il selfie di gruppo"]'::jsonb, 0, 'spogliatoio'),
  (296, 'Quale calciatore è noto per il gesto di dedicare ogni gol al cielo indicando verso l''alto?', '["Molti calciatori religiosi, tra cui Kaká","Solo Ronaldinho","Solo Neymar","Nessuno, è un gesto raro"]'::jsonb, 0, 'spogliatoio'),
  (297, 'In quale storica intervista post-partita un allenatore rispose in modo scherzoso "I say Manchester United, you say Manchester United!"?', '["Kevin Keegan (celebre sfogo su Alex Ferguson, 1996)","Alex Ferguson","Arsène Wenger","José Mourinho"]'::jsonb, 0, 'spogliatoio'),
  (298, 'Quale allenatore inglese ebbe il celebre sfogo televisivo "I would love it if we beat them!" nel 1996?', '["Kevin Keegan","Alex Ferguson","Kenny Dalglish","Terry Venables"]'::jsonb, 0, 'spogliatoio'),
  (299, 'Quale celebre gesto di festa collettiva è tradizione dopo la vittoria di uno Scudetto, con giro di campo e maglia della squadra?', '["Il giro di campo con la coppa/scudetto","Il silenzio in spogliatoio","L''uscita immediata dallo stadio","Nessuna tradizione specifica"]'::jsonb, 0, 'spogliatoio'),
  (300, 'Quale celebre discorso pre-partita, mostrato in un documentario, è attribuito a molti allenatori come motto "Give everything, leave nothing"?', '["Un classico discorso motivazionale da spogliatoio","Una frase mai realmente pronunciata","Un motto esclusivo di un solo allenatore","Una citazione letteraria"]'::jsonb, 0, 'spogliatoio'),
  (301, 'Quale sponsor tecnico rifornisce le maglie della Nazionale Italiana di calcio?', '["Puma","Nike","Adidas","Macron"]'::jsonb, 0, 'maglie_sponsor'),
  (302, 'Quale sponsor tecnico veste la Nazionale brasiliana dagli anni ''90?', '["Nike","Adidas","Puma","Umbro"]'::jsonb, 0, 'maglie_sponsor'),
  (303, 'Di che colore è la storica maglia da trasferta dell''Inghilterra, usata anche nella finale Mondiale 1966?', '["Rossa","Blu","Bianca","Nera"]'::jsonb, 0, 'maglie_sponsor'),
  (304, 'Quali colori caratterizzano storicamente la maglia della nazionale argentina?', '["Bianco e celeste a righe verticali","Bianco e blu a scacchi","Verde e giallo","Rosso e nero"]'::jsonb, 0, 'maglie_sponsor'),
  (305, 'Quale numero di maglia ha indossato Diego Maradona con l''Argentina?', '["9","10","7","11"]'::jsonb, 1, 'maglie_sponsor'),
  (306, 'Quale numero di maglia ha reso celebre Pelé con il Brasile?', '["9","10","7","11"]'::jsonb, 1, 'maglie_sponsor'),
  (307, 'Quale numero di maglia è tradizionalmente associato al ruolo di portiere nel calcio classico?', '["1","12","99","0"]'::jsonb, 0, 'maglie_sponsor'),
  (308, 'Quale squadra italiana ha la celebre maglia a strisce verticali bianconere?', '["Juventus","Milan","Inter","Napoli"]'::jsonb, 0, 'maglie_sponsor'),
  (309, 'Quale squadra italiana indossa la celebre maglia nerazzurra a strisce verticali?', '["Inter","Juventus","Milan","Atalanta"]'::jsonb, 0, 'maglie_sponsor'),
  (310, 'Quali colori sociali rappresentano il Milan nella sua celebre maglia a strisce verticali?', '["Rosso e nero","Blu e nero","Rosso e blu","Bianco e nero"]'::jsonb, 0, 'maglie_sponsor'),
  (311, 'Quale squadra spagnola è nota per la maglia completamente bianca, da cui il soprannome "Los Blancos"?', '["Real Madrid","Barcellona","Atletico Madrid","Valencia"]'::jsonb, 0, 'maglie_sponsor'),
  (312, 'Quale squadra spagnola indossa la celebre maglia blaugrana (blu e granata)?', '["Barcellona","Real Madrid","Siviglia","Betis"]'::jsonb, 0, 'maglie_sponsor'),
  (313, 'Quale organizzazione apparve per la prima volta sulle maglie del Barcellona nel 2006 (in forma di donazione, non sponsor pagante)?', '["UNICEF","Qatar Airways","Nike","Beko"]'::jsonb, 0, 'maglie_sponsor'),
  (314, 'Quale compagnia aerea fu lo sponsor principale del Barcellona dal 2013 circa?', '["Qatar Airways","UNICEF","Rakuten","Spotify"]'::jsonb, 0, 'maglie_sponsor'),
  (315, 'Quale azienda giapponese di e-commerce sostituì Qatar Airways come sponsor del Barcellona?', '["Rakuten","Beko","Spotify","Nike"]'::jsonb, 0, 'maglie_sponsor'),
  (316, 'Quale storico sponsor italiano di pneumatici comparve per decenni sulle maglie dell''Inter?', '["Pirelli","Michelin","Goodyear","Bridgestone"]'::jsonb, 0, 'maglie_sponsor'),
  (317, 'Quale marchio a tre strisce vestiva il Milan negli anni ''80-''90?', '["Adidas","Nike","Puma","Kappa"]'::jsonb, 0, 'maglie_sponsor'),
  (318, 'Quale marchio sportivo tedesco è celebre per il logo a tre strisce?', '["Adidas","Nike","Puma","Reebok"]'::jsonb, 0, 'maglie_sponsor'),
  (319, 'Quale marchio sportivo statunitense è noto per il celebre logo "swoosh"?', '["Nike","Adidas","Under Armour","Puma"]'::jsonb, 0, 'maglie_sponsor'),
  (320, 'Quale colore predomina nella maglia storica del Napoli?', '["Azzurro","Rosso","Bianco","Verde"]'::jsonb, 0, 'maglie_sponsor'),
  (321, 'Quale colore predomina nella maglia storica della Roma?', '["Giallorosso","Bianconero","Nerazzurro","Rossoblu"]'::jsonb, 0, 'maglie_sponsor'),
  (322, 'Quale colore predomina nella maglia storica della Lazio?', '["Biancoceleste","Giallorosso","Bianconero","Rossonero"]'::jsonb, 0, 'maglie_sponsor'),
  (323, 'Quale colore predomina nella maglia storica della Fiorentina?', '["Viola","Verde","Blu","Arancione"]'::jsonb, 0, 'maglie_sponsor'),
  (324, 'Quale sponsor tecnico veste la Nazionale francese di calcio?', '["Nike","Adidas","Puma","Le Coq Sportif"]'::jsonb, 0, 'maglie_sponsor'),
  (325, 'Quale sponsor tecnico veste storicamente la Nazionale tedesca?', '["Adidas","Nike","Puma","Umbro"]'::jsonb, 0, 'maglie_sponsor'),
  (326, 'Quale marchio sportivo tedesco, rivale di Adidas, fu fondato dal fratello del fondatore Adidas?', '["Puma","Nike","Reebok","Kappa"]'::jsonb, 0, 'maglie_sponsor'),
  (327, 'Quale squadra inglese, soprannominata "The Reds", ha la maglia rossa come colore sociale principale?', '["Liverpool","Manchester City","Chelsea","Tottenham"]'::jsonb, 0, 'maglie_sponsor'),
  (328, 'Quale squadra inglese, soprannominata "The Red Devils", indossa la maglia rossa?', '["Manchester United","Liverpool","Arsenal","Everton"]'::jsonb, 0, 'maglie_sponsor'),
  (329, 'Quale squadra inglese indossa storicamente la maglia blu reale, soprannominata "The Blues"?', '["Chelsea","Manchester United","Liverpool","Tottenham"]'::jsonb, 0, 'maglie_sponsor'),
  (330, 'Quale squadra inglese, soprannominata "Gunners", ha la celebre maglia rossa con colletto e maniche bianche?', '["Arsenal","Aston Villa","West Ham","Fulham"]'::jsonb, 0, 'maglie_sponsor'),
  (331, 'Quale numero di maglia indossava Zinedine Zidane con la Francia e il Real Madrid?', '["10","5","7","9"]'::jsonb, 0, 'maglie_sponsor'),
  (332, 'Quale numero di maglia rese celebre Ronaldinho al Barcellona?', '["10","9","7","11"]'::jsonb, 0, 'maglie_sponsor'),
  (333, 'Quale numero di maglia ha sempre indossato Cristiano Ronaldo al Real Madrid?', '["7","9","10","11"]'::jsonb, 0, 'maglie_sponsor'),
  (334, 'Quale numero di maglia indossa storicamente Lionel Messi?', '["10","9","7","11"]'::jsonb, 0, 'maglie_sponsor'),
  (335, 'Quale numero di maglia scelse Neymar al PSG?', '["10","9","7","11"]'::jsonb, 0, 'maglie_sponsor'),
  (336, 'Quale numero di maglia indossava Ronaldo "il Fenomeno" con la Nazionale brasiliana?', '["9","10","11","7"]'::jsonb, 0, 'maglie_sponsor'),
  (337, 'Di che colori è la maglia storica del Boca Juniors?', '["Blu e oro/giallo","Bianco e celeste","Rosso e bianco","Verde e bianco"]'::jsonb, 0, 'maglie_sponsor'),
  (338, 'Di che colori è la maglia storica del River Plate?', '["Bianco con banda rossa diagonale","Blu e oro","Rosso e bianco","Verde e nero"]'::jsonb, 0, 'maglie_sponsor'),
  (339, 'Quale squadra portoghese ha la celebre maglia biancoverde?', '["Sporting Lisbona","Benfica","Porto","Braga"]'::jsonb, 0, 'maglie_sponsor'),
  (340, 'Quale squadra portoghese, soprannominata "As Águias" (le aquile), indossa la maglia rossa?', '["Benfica","Sporting","Porto","Vitória Guimarães"]'::jsonb, 0, 'maglie_sponsor'),
  (341, 'Quale squadra portoghese ha la celebre maglia a strisce blu e bianche?', '["Porto","Benfica","Sporting","Braga"]'::jsonb, 0, 'maglie_sponsor'),
  (342, 'Quale colore predomina nella maglia storica del Borussia Dortmund, soprannominato "Die Schwarzgelben"?', '["Giallo e nero","Rosso e bianco","Blu e bianco","Verde e bianco"]'::jsonb, 0, 'maglie_sponsor'),
  (343, 'Quale colore predomina nella maglia storica del Bayern Monaco?', '["Rosso","Blu","Verde","Giallo"]'::jsonb, 0, 'maglie_sponsor'),
  (344, 'Quale azienda di telecomunicazioni tedesca è storico sponsor principale del Bayern Monaco dal 2002?', '["Deutsche Telekom","Allianz","Audi","Adidas"]'::jsonb, 0, 'maglie_sponsor'),
  (345, 'Quale marchio automobilistico tedesco possiede quote societarie del Bayern Monaco?', '["Audi","BMW","Mercedes","Volkswagen"]'::jsonb, 0, 'maglie_sponsor'),
  (346, 'Quale nazionale ha come colore sociale storico la maglia bianca (Italia in trasferta)?', '["Italia","Francia","Germania","Spagna"]'::jsonb, 0, 'maglie_sponsor'),
  (347, 'Quale colore ha la maglia home storica della Nazionale Italiana?', '["Azzurro","Bianco","Verde","Rosso"]'::jsonb, 0, 'maglie_sponsor'),
  (348, 'Da cosa deriva il colore "azzurro" della maglia della Nazionale Italiana, assente nella bandiera tricolore?', '["Colore araldico di Casa Savoia","Scelta casuale","Colore dello sponsor tecnico","Eredità dal calcio inglese"]'::jsonb, 0, 'maglie_sponsor'),
  (349, 'Quale nazionale ha la maglia interamente arancione come colore sociale distintivo?', '["Olanda","Belgio","Danimarca","Svezia"]'::jsonb, 0, 'maglie_sponsor'),
  (350, 'Quale nazionale ha la celebre maglia gialla con inserti verdi, tra le più iconiche al mondo?', '["Brasile","Colombia","Nigeria","Australia"]'::jsonb, 0, 'maglie_sponsor')
on conflict (id) do nothing;
